task_label_mapping_zalando_germany = {
    'Color': {'Missing': 0,
           'Other': 1,
           'black': 2,
           'blue': 3,
           'beige': 4,
           'green': 5,
           'grey': 6,
           'brown': 7,
           'pink': 8,
           'white': 9,
           'purple': 10,
           'orange': 11,
           'red': 12,
           'silver': 13,
           'yellow': 14,
           'gold': 15},
 'Fabric': {'Missing': 0,
            'Other': 1,
            'Jersey': 2,
            'Chiffon': 3,
            'Knit': 4,
            'Satin': 5,
            'Rib': 6,
            'Denim': 7,
            'Tulle': 8,
            'Lace': 9,
            'Sweat': 10,
            'Mixed': 11,
            'Mesh': 12,
            'Velvet/velour': 13,
            'Piqué': 14,
            'Crocheted': 15,
            'Faux leather': 16,
            'Cord': 17},
 'Fit': {'Missing': 0,
         'Other': 1,
         'Regular Fit': 2,
         'Slim Fit': 3,
         'Loose Fit': 4,
         'Skinny Fit': 5,
         'Oversized': 6,
         'Fitted waist': 7,
         'Normal fit': 8},
 'Neckline': {'Missing': 0,
              'Other': 1,
              'Crew neck': 2,
              'Low-cut v-neck': 3,
              'Backless': 4,
              'Cache-coeur': 5,
              'V-neck': 6,
              'Scoop neck': 7,
              'Boat neck': 8,
              'Square neck': 9,
              'Off-the-shoulder': 10,
              'Henley': 11,
              'Cowl neck': 12},
 'Pattern': {'Missing': 0,
             'Other': 1,
             'Plain': 2,
             'Print': 3,
             'Floral': 4,
             'Marl': 5,
             'Striped': 6,
             'Animal print': 7,
             'Polka dot': 8,
             'Paisley': 9,
             'Checked': 10,
             'Colourful': 11,
             'Colour gradient': 12,
             'Herringbone': 13,
             'Pinstriped': 14,
             'Camouflage': 15},
 'Collar': {'Missing': 0,
            'Other': 1,
            'Standing collar': 2,
            'Turn-down collar': 3,
            'Polo neck': 4,
            'Hood': 5,
            'Volant collar': 6,
            'Polo shirt': 7,
            'Lapel collar': 8,
            'Shawl collar': 9,
            'Zip neck': 10,
            'High collar': 11,
            'Mandarin collar': 12,
            'Shirt collar': 13,
            'Button down': 14,
            'Peter Pan collar': 15,
            'Contrasting collar': 16},
 'Length': {'Missing': 0,
            'Other': 1,
            'Calf-length': 2,
            'Short': 3,
            'Knee-length': 4,
            'Long': 5,
            'Extra short': 6,
            'Thigh-length': 7,
            'Extra long': 8},
 'Shape': {'Missing': 0,
           'Other': 1,
           'Fitted': 2,
           'Straight': 3,
           'Flared': 4,
           'Body-hugging': 5,
           'Cocoon': 6,
           'Tapered': 7},
 'Sleeve_Length': {'Missing': 0,
                   'Other': 1,
                   'Long': 2,
                   'Short': 3,
                   'Sleeveless': 4,
                   '34 length': 5,
                   'Spaghetti straps': 6,
                   'Extra short': 7,
                   'Elbow length': 8,
                   'Extra long': 9,
                   'Mixed': 10,
                   'Strapless': 11,
                   'Sleeveless, strapless': 12}}



zalando_label_mappings = {
    'zalando_germany': task_label_mapping_zalando_germany
}

class Labels():
    def __init__(self, dataset_name: str):

        if dataset_name.startswith('zalando'):
            self.task_mapping = zalando_label_mappings[dataset_name]
            self.task_label_dims = [len(c) for c in self.task_mapping.values()]
        else:
            raise ValueError(f'No labels specified for dataset \'{dataset_name}\'')

    def get_task_index(self, task: str) -> int:
        return list(self.task_mapping.keys()).index(task)