task_label_mapping_zalando_germany = {
    'Color': {'brown': 0,
           'beige': 1,
           'blue': 2,
           'black': 3,
           'grey': 4,
           'green': 5,
           'red': 6,
           'orange': 7,
           'pink': 8,
           'purple': 9,
           'yellow': 10,
           'gold': 11,
           'silver': 12,
           'white': 13},
 'Fabric': {'Jersey': 0,
            'Missing': 1,
            'Chiffon': 2,
            'Knit': 3,
            'Rib': 4,
            'Sweat': 5,
            'Mixed': 6,
            'Satin': 7,
            'Lace': 8,
            'Velvet/velour': 9,
            'Cord': 10,
            'Crocheted': 11,
            'Mesh': 12,
            'Piqué': 13,
            'Tulle': 14,
            'Other': 15,
            'Denim': 16,
            'Faux leather': 17},
 'Fit': {'Slim Fit': 0,
         'Regular Fit': 1,
         'Loose Fit': 2,
         'Skinny Fit': 3,
         'Fitted waist': 4,
         'Missing': 5,
         'Oversized': 6,
         'Normal fit': 7},
 'Neckline': {'Missing': 0,
              'Low-cut v-neck': 1,
              'Crew neck': 2,
              'V-neck': 3,
              'Scoop neck': 4,
              'Backless': 5,
              'Cache-coeur': 6,
              'Square neck': 7,
              'Boat neck': 8,
              'Henley': 9,
              'Off-the-shoulder': 10,
              'Other': 11,
              'Cowl neck': 12},
 'Pattern': {'Plain': 0,
             'Print': 1,
             'Floral': 2,
             'Colourful': 3,
             'Animal print': 4,
             'Marl': 5,
             'Striped': 6,
             'Paisley': 7,
             'Polka dot': 8,
             'Missing': 9,
             'Camouflage': 10,
             'Checked': 11,
             'Colour gradient': 12,
             'Other': 13,
             'Herringbone': 14,
             'Pinstriped': 15},
 'Collar': {'Standing collar': 0,
            'Missing': 1,
            'Shawl collar': 2,
            'Turn-down collar': 3,
            'Polo shirt': 4,
            'Contrasting collar': 5,
            'Hood': 6,
            'High collar': 7,
            'Volant collar': 8,
            'Polo neck': 9,
            'Mandarin collar': 10,
            'Zip neck': 11,
            'Shirt collar': 12,
            'Button down': 13,
            'Lapel collar': 14,
            'Other': 15,
            'Peter Pan collar': 16},
 'Length': {'Calf-length': 0,
            'Knee-length': 1,
            'Short': 2,
            'Long': 3,
            'Extra short': 4,
            'Thigh-length': 5,
            'Extra long': 6,
            'Other': 7,
            'Missing': 8},
 'Shape': {'Body-hugging': 0,
           'Fitted': 1,
           'Flared': 2,
           'Missing': 3,
           'Straight': 4,
           'Tapered': 5,
           'Cocoon': 6},
 'Sleeve_Length': {'Short': 0,
                   'Sleeveless': 1,
                   '34 length': 2,
                   'Mixed': 3,
                   'Extra short': 4,
                   'Spaghetti straps': 5,
                   'Strapless': 6,
                   'Elbow length': 7,
                   'Long': 8,
                   'Extra long': 9,
                   'Sleeveless, strapless': 10,
                   'Missing': 11}}



zalando_label_mappings = {
    'zalando_germany': task_label_mapping_zalando_germany
}

class Labels():
    def __init__(self, dataset_name: str):

        if dataset_name.startswith('zalando'):
            self.task_mapping = zalando_label_mappings[dataset_name]
            self.task_label_dims = [len(c) for c in self.task_mapping.values()]
        else:
            raise ValueError(f'No labels specified for dataset \'{dataset_name}\'')

    def get_task_index(self, task: str) -> int:
        return list(self.task_mapping.keys()).index(task)